// ISO-3166-1 alpha-2 country code -> lowercase name aliases. Used to match an
// event's geography (country names) to a live channel's country tag (iptv-org
// sets `region` to a 2-letter country code), so an event can surface a channel
// from its OWN country. Not exhaustive — covers the news-relevant set; codes not
// listed simply fall back to keyword/region matching.
export const COUNTRY_NAMES = {
  US: ["united states", "u.s.", "usa", "america"],
  GB: ["united kingdom", "britain", "u.k.", "england", "scotland", "wales", "london"],
  FR: ["france", "french", "paris"],
  DE: ["germany", "german", "berlin"],
  IT: ["italy", "italian", "rome"],
  ES: ["spain", "spanish", "madrid"],
  PT: ["portugal", "lisbon"],
  NL: ["netherlands", "dutch", "amsterdam"],
  BE: ["belgium", "brussels"],
  CH: ["switzerland", "swiss", "geneva"],
  AT: ["austria", "vienna"],
  IE: ["ireland", "dublin"],
  SE: ["sweden", "stockholm"],
  NO: ["norway", "oslo"],
  DK: ["denmark", "copenhagen"],
  FI: ["finland", "helsinki"],
  PL: ["poland", "polish", "warsaw"],
  UA: ["ukraine", "ukrainian", "kyiv", "kiev"],
  RU: ["russia", "russian", "moscow"],
  TR: ["turkey", "türkiye", "turkish", "ankara", "istanbul"],
  GR: ["greece", "greek", "athens"],
  RO: ["romania", "bucharest"],
  CZ: ["czech", "czechia", "prague"],
  HU: ["hungary", "budapest"],
  IL: ["israel", "israeli", "jerusalem", "tel aviv"],
  PS: ["palestine", "palestinian", "gaza", "west bank"],
  LB: ["lebanon", "beirut"],
  SY: ["syria", "syrian", "damascus"],
  IQ: ["iraq", "iraqi", "baghdad"],
  IR: ["iran", "iranian", "tehran", "persian gulf"],
  SA: ["saudi arabia", "saudi", "riyadh"],
  AE: ["united arab emirates", "uae", "dubai", "abu dhabi"],
  QA: ["qatar", "doha"],
  YE: ["yemen", "sanaa", "bab-el-mandeb"],
  EG: ["egypt", "egyptian", "cairo", "suez", "nile"],
  JO: ["jordan", "amman"],
  KW: ["kuwait"],
  IN: ["india", "indian", "delhi", "mumbai", "kashmir"],
  PK: ["pakistan", "pakistani", "islamabad", "karachi"],
  BD: ["bangladesh", "dhaka"],
  LK: ["sri lanka", "colombo"],
  NP: ["nepal", "kathmandu"],
  AF: ["afghanistan", "kabul"],
  CN: ["china", "chinese", "beijing", "shanghai", "hong kong"],
  JP: ["japan", "japanese", "tokyo"],
  KR: ["south korea", "korea", "seoul"],
  KP: ["north korea", "pyongyang"],
  TW: ["taiwan", "taipei"],
  SG: ["singapore"],
  MY: ["malaysia", "kuala lumpur", "malacca"],
  ID: ["indonesia", "jakarta"],
  PH: ["philippines", "manila", "sarangani"],
  TH: ["thailand", "bangkok"],
  VN: ["vietnam", "hanoi"],
  MM: ["myanmar", "burma", "yangon"],
  AU: ["australia", "australian", "sydney", "melbourne"],
  NZ: ["new zealand", "auckland", "wellington"],
  CA: ["canada", "canadian", "ottawa", "toronto"],
  MX: ["mexico", "mexican", "mexico city"],
  BR: ["brazil", "brazilian", "rio", "sao paulo", "brasilia"],
  AR: ["argentina", "buenos aires"],
  CL: ["chile", "santiago"],
  CO: ["colombia", "bogota"],
  VE: ["venezuela", "venezuelan", "caracas", "yumare"],
  PE: ["peru", "lima"],
  EC: ["ecuador", "quito"],
  ZA: ["south africa", "johannesburg", "cape town"],
  NG: ["nigeria", "lagos", "abuja"],
  KE: ["kenya", "nairobi"],
  ET: ["ethiopia", "addis ababa"],
  SD: ["sudan", "khartoum"],
  SO: ["somalia", "mogadishu"],
  MA: ["morocco", "rabat", "casablanca"],
  DZ: ["algeria", "algiers"],
  TN: ["tunisia", "tunis"],
  LY: ["libya", "tripoli"],
  MG: ["madagascar"],
};
