LAUNCH_SOURCES = [
    {
        "name": "Reuters",
        "url": "https://www.reuters.com",
        "rss_url": "https://feeds.reuters.com/reuters/topNews",
        "country": "US",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "France 24",
        "url": "https://www.france24.com",
        "rss_url": "https://www.france24.com/en/rss",
        "country": "FR",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Financial Times",
        "url": "https://www.ft.com",
        "rss_url": "https://www.ft.com/rss/home",
        "country": "UK",
        "category": "economy",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Bloomberg",
        "url": "https://www.bloomberg.com",
        "rss_url": "https://feeds.bloomberg.com/markets/news.rss",
        "country": "US",
        "category": "economy",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com",
        "rss_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "country": "QA",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "BBC News",
        "url": "https://www.bbc.com/news",
        "rss_url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "country": "UK",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "The Hindu",
        "url": "https://www.thehindu.com",
        "rss_url": "https://www.thehindu.com/news/international/?service=rss",
        "country": "IN",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Nikkei Asia",
        "url": "https://asia.nikkei.com",
        "rss_url": "https://asia.nikkei.com/rss/feed/nar",
        "country": "JP",
        "category": "economy",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Foreign Policy",
        "url": "https://foreignpolicy.com",
        "rss_url": "https://foreignpolicy.com/feed/",
        "country": "US",
        "category": "geopolitics",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Reuters Commodities",
        "url": "https://www.reuters.com/markets/commodities",
        "rss_url": "https://feeds.reuters.com/reuters/commoditiesNews",
        "country": "US",
        "category": "commodities",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Radio Free Europe",
        "url": "https://www.rferl.org",
        "rss_url": "https://www.rferl.org/api/epiqq",
        "country": "US",
        "category": "geopolitics",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Brookings Institution",
        "url": "https://www.brookings.edu",
        "rss_url": "https://www.brookings.edu/feed/",
        "country": "US",
        "category": "policy",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Carbon Brief",
        "url": "https://www.carbonbrief.org",
        "rss_url": "https://www.carbonbrief.org/feed/",
        "country": "UK",
        "category": "climate",
        "bias_rating": "left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Crisis Group",
        "url": "https://www.crisisgroup.org",
        "rss_url": "https://www.crisisgroup.org/rss.xml",
        "country": "BE",
        "category": "conflict",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Straits Times",
        "url": "https://www.straitstimes.com",
        "rss_url": "https://www.straitstimes.com/rss.xml",
        "country": "SG",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Daily Nation Kenya",
        "url": "https://nation.africa",
        "rss_url": "https://nation.africa/kenya/rss.xml",
        "country": "KE",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "South China Morning Post",
        "url": "https://www.scmp.com",
        "rss_url": "https://www.scmp.com/rss/91/feed",
        "country": "HK",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Deutsche Welle",
        "url": "https://www.dw.com",
        "rss_url": "https://rss.dw.com/rdf/rss-en-world",
        "country": "DE",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "The Guardian",
        "url": "https://www.theguardian.com",
        "rss_url": "https://www.theguardian.com/world/rss",
        "country": "UK",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "OilPrice",
        "url": "https://oilprice.com",
        "rss_url": "https://oilprice.com/rss/main",
        "country": "US",
        "category": "commodities",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },

    # ── Expanded coverage (beta) — compact entries, same schema. Dead/blocked
    # feeds fail soft (engine.py logs & skips), so over-listing is safe. ─────────
    # North America
    {"name": "NPR", "url": "https://www.npr.org", "rss_url": "https://feeds.npr.org/1001/rss.xml", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "PBS NewsHour", "url": "https://www.pbs.org/newshour", "rss_url": "https://www.pbs.org/newshour/feeds/rss/headlines", "country": "US", "category": "general", "bias_rating": "center", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Politico", "url": "https://www.politico.com", "rss_url": "https://rss.politico.com/politics-news.xml", "country": "US", "category": "policy", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "The Hill", "url": "https://thehill.com", "rss_url": "https://thehill.com/news/feed/", "country": "US", "category": "policy", "bias_rating": "center", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "CNBC", "url": "https://www.cnbc.com", "rss_url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362", "country": "US", "category": "economy", "bias_rating": "center", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "MarketWatch", "url": "https://www.marketwatch.com", "rss_url": "https://feeds.marketwatch.com/marketwatch/topstories/", "country": "US", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "New York Times — World", "url": "https://www.nytimes.com/section/world", "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "New York Times — Business", "url": "https://www.nytimes.com/section/business", "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "country": "US", "category": "economy", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Washington Post — World", "url": "https://www.washingtonpost.com", "rss_url": "https://feeds.washingtonpost.com/rss/world", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Los Angeles Times — World", "url": "https://www.latimes.com", "rss_url": "https://www.latimes.com/world/rss2.0.xml", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "CBS News — World", "url": "https://www.cbsnews.com", "rss_url": "https://www.cbsnews.com/latest/rss/world", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "ABC News — International", "url": "https://abcnews.go.com", "rss_url": "https://abcnews.go.com/abcnews/internationalheadlines", "country": "US", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "The Atlantic", "url": "https://www.theatlantic.com", "rss_url": "https://www.theatlantic.com/feed/all/", "country": "US", "category": "policy", "bias_rating": "left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Axios", "url": "https://www.axios.com", "rss_url": "https://api.axios.com/feed/", "country": "US", "category": "general", "bias_rating": "center", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "ProPublica", "url": "https://www.propublica.org", "rss_url": "https://www.propublica.org/feeds/propublica/main", "country": "US", "category": "policy", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "CBC — World", "url": "https://www.cbc.ca", "rss_url": "https://www.cbc.ca/webfeed/rss/rss-world", "country": "CA", "category": "general", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "CTV News — World", "url": "https://www.ctvnews.ca", "rss_url": "https://www.ctvnews.ca/rss/ctvnews-ca-world-public-rss-1.822289", "country": "CA", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Europe
    {"name": "Euronews", "url": "https://www.euronews.com", "rss_url": "https://www.euronews.com/rss?level=theme&name=news", "country": "FR", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Le Monde (EN)", "url": "https://www.lemonde.fr/en", "rss_url": "https://www.lemonde.fr/en/rss/une.xml", "country": "FR", "category": "general", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Spiegel International", "url": "https://www.spiegel.de/international", "rss_url": "https://www.spiegel.de/international/index.rss", "country": "DE", "category": "general", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "ANSA English", "url": "https://www.ansa.it/english", "rss_url": "https://www.ansa.it/english/english_rss.xml", "country": "IT", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Independent — World", "url": "https://www.independent.co.uk", "rss_url": "https://www.independent.co.uk/news/world/rss", "country": "UK", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "The Telegraph — World", "url": "https://www.telegraph.co.uk", "rss_url": "https://www.telegraph.co.uk/world-news/rss.xml", "country": "UK", "category": "general", "bias_rating": "center-right", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Politico Europe", "url": "https://www.politico.eu", "rss_url": "https://www.politico.eu/feed/", "country": "BE", "category": "policy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "EUobserver", "url": "https://euobserver.com", "rss_url": "https://euobserver.com/rss", "country": "BE", "category": "policy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Balkan Insight", "url": "https://balkaninsight.com", "rss_url": "https://balkaninsight.com/feed/", "country": "RS", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "RTÉ News", "url": "https://www.rte.ie/news", "rss_url": "https://www.rte.ie/news/rss/news-headlines.xml", "country": "IE", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Moscow Times", "url": "https://www.themoscowtimes.com", "rss_url": "https://www.themoscowtimes.com/rss/news", "country": "RU", "category": "geopolitics", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Kyiv Independent", "url": "https://kyivindependent.com", "rss_url": "https://kyivindependent.com/feed/", "country": "UA", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Middle East
    {"name": "The Times of Israel", "url": "https://www.timesofisrael.com", "rss_url": "https://www.timesofisrael.com/feed/", "country": "IL", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Jerusalem Post", "url": "https://www.jpost.com", "rss_url": "https://www.jpost.com/rss/rssfeedsheadlines.aspx", "country": "IL", "category": "general", "bias_rating": "center-right", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Middle East Eye", "url": "https://www.middleeasteye.net", "rss_url": "https://www.middleeasteye.net/rss", "country": "UK", "category": "conflict", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Arab News", "url": "https://www.arabnews.com", "rss_url": "https://www.arabnews.com/rss.xml", "country": "SA", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Al-Monitor", "url": "https://www.al-monitor.com", "rss_url": "https://www.al-monitor.com/rss", "country": "US", "category": "geopolitics", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # South & East Asia
    {"name": "The Times of India — World", "url": "https://timesofindia.indiatimes.com", "rss_url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", "country": "IN", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "NDTV — World", "url": "https://www.ndtv.com", "rss_url": "https://feeds.feedburner.com/ndtvnews-world-news", "country": "IN", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Hindustan Times — World", "url": "https://www.hindustantimes.com", "rss_url": "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml", "country": "IN", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Indian Express — World", "url": "https://indianexpress.com", "rss_url": "https://indianexpress.com/section/world/feed/", "country": "IN", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Dawn", "url": "https://www.dawn.com", "rss_url": "https://www.dawn.com/feeds/home", "country": "PK", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Japan Times", "url": "https://www.japantimes.co.jp", "rss_url": "https://www.japantimes.co.jp/feed/", "country": "JP", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Kyodo News", "url": "https://english.kyodonews.net", "rss_url": "https://english.kyodonews.net/rss/news.xml", "country": "JP", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Korea Herald", "url": "https://www.koreaherald.com", "rss_url": "https://www.koreaherald.com/rss/020000000000.xml", "country": "KR", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Channel NewsAsia", "url": "https://www.channelnewsasia.com", "rss_url": "https://www.channelnewsasia.com/rssfeeds/8395986", "country": "SG", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Bangkok Post", "url": "https://www.bangkokpost.com", "rss_url": "https://www.bangkokpost.com/rss/data/most-recent.xml", "country": "TH", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Diplomat", "url": "https://thediplomat.com", "rss_url": "https://thediplomat.com/feed/", "country": "US", "category": "geopolitics", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Oceania
    {"name": "ABC Australia", "url": "https://www.abc.net.au/news", "rss_url": "https://www.abc.net.au/news/feed/51120/rss.xml", "country": "AU", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Sydney Morning Herald — World", "url": "https://www.smh.com.au", "rss_url": "https://www.smh.com.au/rss/world.xml", "country": "AU", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "RNZ — World", "url": "https://www.rnz.co.nz", "rss_url": "https://www.rnz.co.nz/rss/world.xml", "country": "NZ", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Africa & Latin America
    {"name": "AllAfrica", "url": "https://allafrica.com", "rss_url": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", "country": "MU", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Mail & Guardian", "url": "https://mg.co.za", "rss_url": "https://mg.co.za/feed/", "country": "ZA", "category": "general", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "News24 — World", "url": "https://www.news24.com", "rss_url": "https://feeds.news24.com/articles/news24/World/rss", "country": "ZA", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Premium Times", "url": "https://www.premiumtimesng.com", "rss_url": "https://www.premiumtimesng.com/feed", "country": "NG", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "MercoPress", "url": "https://en.mercopress.com", "rss_url": "https://en.mercopress.com/rss/", "country": "UY", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Rio Times", "url": "https://www.riotimesonline.com", "rss_url": "https://www.riotimesonline.com/feed/", "country": "BR", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Technology & science
    {"name": "Ars Technica", "url": "https://arstechnica.com", "rss_url": "https://feeds.arstechnica.com/arstechnica/index", "country": "US", "category": "technology", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "MIT Technology Review", "url": "https://www.technologyreview.com", "rss_url": "https://www.technologyreview.com/feed/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Verge", "url": "https://www.theverge.com", "rss_url": "https://www.theverge.com/rss/index.xml", "country": "US", "category": "technology", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Wired", "url": "https://www.wired.com", "rss_url": "https://www.wired.com/feed/rss", "country": "US", "category": "technology", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "TechCrunch", "url": "https://techcrunch.com", "rss_url": "https://techcrunch.com/feed/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Nature News", "url": "https://www.nature.com", "rss_url": "https://www.nature.com/nature.rss", "country": "UK", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "ScienceDaily", "url": "https://www.sciencedaily.com", "rss_url": "https://www.sciencedaily.com/rss/top/science.xml", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Conversation", "url": "https://theconversation.com", "rss_url": "https://theconversation.com/global/articles.atom", "country": "AU", "category": "policy", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    # Defense, conflict & security
    {"name": "Defense One", "url": "https://www.defenseone.com", "rss_url": "https://www.defenseone.com/rss/all/", "country": "US", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "War on the Rocks", "url": "https://warontherocks.com", "rss_url": "https://warontherocks.com/feed/", "country": "US", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Defense Post", "url": "https://thedefensepost.com", "rss_url": "https://thedefensepost.com/feed/", "country": "US", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Lawfare", "url": "https://www.lawfaremedia.org", "rss_url": "https://www.lawfaremedia.org/feed/rss.xml", "country": "US", "category": "policy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Economy, energy & commodities
    {"name": "gCaptain", "url": "https://gcaptain.com", "rss_url": "https://gcaptain.com/feed/", "country": "US", "category": "commodities", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Mining.com", "url": "https://www.mining.com", "rss_url": "https://www.mining.com/feed/", "country": "CA", "category": "commodities", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Inside Climate News", "url": "https://insideclimatenews.org", "rss_url": "https://insideclimatenews.org/feed/", "country": "US", "category": "climate", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Grist", "url": "https://grist.org", "rss_url": "https://grist.org/feed/", "country": "US", "category": "climate", "bias_rating": "left", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Energy Mix", "url": "https://www.theenergymix.com", "rss_url": "https://www.theenergymix.com/feed/", "country": "CA", "category": "climate", "bias_rating": "center-left", "bias_source": "mbfc", "scrape_method": "rss"},
    # Additional wires & sector desks
    {"name": "BBC — Business", "url": "https://www.bbc.com/news/business", "rss_url": "https://feeds.bbci.co.uk/news/business/rss.xml", "country": "UK", "category": "economy", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "BBC — Technology", "url": "https://www.bbc.com/news/technology", "rss_url": "https://feeds.bbci.co.uk/news/technology/rss.xml", "country": "UK", "category": "technology", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "The Guardian — Business", "url": "https://www.theguardian.com/business", "rss_url": "https://www.theguardian.com/business/rss", "country": "UK", "category": "economy", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "The Guardian — US", "url": "https://www.theguardian.com/us-news", "rss_url": "https://www.theguardian.com/us-news/rss", "country": "UK", "category": "general", "bias_rating": "center-left", "bias_source": "allsides", "scrape_method": "rss"},
    {"name": "Sky News — World", "url": "https://news.sky.com/world", "rss_url": "https://feeds.skynews.com/feeds/rss/world.xml", "country": "UK", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Foreign Affairs", "url": "https://www.foreignaffairs.com", "rss_url": "https://www.foreignaffairs.com/rss.xml", "country": "US", "category": "geopolitics", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Defense News", "url": "https://www.defensenews.com", "rss_url": "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", "country": "US", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Economic Times", "url": "https://economictimes.indiatimes.com", "rss_url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms", "country": "IN", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Business Standard", "url": "https://www.business-standard.com", "rss_url": "https://www.business-standard.com/rss/home_page_top_stories.rss", "country": "IN", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Yonhap News", "url": "https://en.yna.co.kr", "rss_url": "https://en.yna.co.kr/RSS/news.xml", "country": "KR", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Deutsche Welle — Business", "url": "https://www.dw.com/en/business", "rss_url": "https://rss.dw.com/rdf/rss-en-bus", "country": "DE", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Rest of World", "url": "https://restofworld.org", "rss_url": "https://restofworld.org/feed/latest/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},

    # ── Batch 2 (5-min cadence expansion) — additional keyless RSS across OSINT/
    # investigative, humanitarian, state wires, Asia economy, maritime/trade and
    # cyber-threat. Same fail-soft rule: dead feeds are logged & skipped. ─────────
    # State wires & broad international
    {"name": "Deutsche Welle", "url": "https://www.dw.com/en", "rss_url": "https://rss.dw.com/rdf/rss-en-all", "country": "DE", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Semafor", "url": "https://www.semafor.com", "rss_url": "https://www.semafor.com/rss.xml", "country": "US", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Anadolu Agency", "url": "https://www.aa.com.tr/en", "rss_url": "https://www.aa.com.tr/en/rss/default?cat=live", "country": "TR", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Al Arabiya English", "url": "https://english.alarabiya.net", "rss_url": "https://english.alarabiya.net/feed/rss2/en.xml", "country": "AE", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "TASS", "url": "https://tass.com", "rss_url": "https://tass.com/rss/v2.xml", "country": "RU", "category": "geopolitics", "bias_rating": "right", "bias_source": "mbfc", "scrape_method": "rss"},
    # Humanitarian, conflict & OSINT/investigative
    {"name": "ReliefWeb", "url": "https://reliefweb.int", "rss_url": "https://reliefweb.int/updates/rss.xml", "country": "CH", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "UN News", "url": "https://news.un.org", "rss_url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "country": "US", "category": "policy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Bellingcat", "url": "https://www.bellingcat.com", "rss_url": "https://www.bellingcat.com/feed/", "country": "NL", "category": "conflict", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "OCCRP", "url": "https://www.occrp.org", "rss_url": "https://www.occrp.org/en/feed", "country": "US", "category": "policy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Asia economy
    {"name": "Nikkei Asia", "url": "https://asia.nikkei.com", "rss_url": "https://asia.nikkei.com/rss/feed/nar", "country": "JP", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "South China Morning Post", "url": "https://www.scmp.com", "rss_url": "https://www.scmp.com/rss/91/feed", "country": "HK", "category": "general", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Caixin Global", "url": "https://www.caixinglobal.com", "rss_url": "https://www.caixinglobal.com/rss/report.xml", "country": "CN", "category": "economy", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Maritime & trade (chokepoint/shipping consequence)
    {"name": "The Maritime Executive", "url": "https://maritime-executive.com", "rss_url": "https://maritime-executive.com/rss", "country": "US", "category": "commodities", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Loadstar", "url": "https://theloadstar.com", "rss_url": "https://theloadstar.com/feed/", "country": "UK", "category": "commodities", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    # Cyber & threat intelligence
    {"name": "BleepingComputer", "url": "https://www.bleepingcomputer.com", "rss_url": "https://www.bleepingcomputer.com/feed/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "The Record", "url": "https://therecord.media", "rss_url": "https://therecord.media/feed/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
    {"name": "Krebs on Security", "url": "https://krebsonsecurity.com", "rss_url": "https://krebsonsecurity.com/feed/", "country": "US", "category": "technology", "bias_rating": "center", "bias_source": "mbfc", "scrape_method": "rss"},
]
