LAUNCH_SOURCES = [
    {
        "name": "Reuters",
        "url": "https://www.reuters.com",
        "rss_url": "https://feeds.reuters.com/reuters/topNews",
        "country": "US",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "France 24",
        "url": "https://www.france24.com",
        "rss_url": "https://www.france24.com/en/rss",
        "country": "FR",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Financial Times",
        "url": "https://www.ft.com",
        "rss_url": "https://www.ft.com/rss/home",
        "country": "UK",
        "category": "economy",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Bloomberg",
        "url": "https://www.bloomberg.com",
        "rss_url": "https://feeds.bloomberg.com/markets/news.rss",
        "country": "US",
        "category": "economy",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com",
        "rss_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "country": "QA",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "BBC News",
        "url": "https://www.bbc.com/news",
        "rss_url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "country": "UK",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "The Hindu",
        "url": "https://www.thehindu.com",
        "rss_url": "https://www.thehindu.com/news/international/?service=rss",
        "country": "IN",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Nikkei Asia",
        "url": "https://asia.nikkei.com",
        "rss_url": "https://asia.nikkei.com/rss/feed/nar",
        "country": "JP",
        "category": "economy",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Foreign Policy",
        "url": "https://foreignpolicy.com",
        "rss_url": "https://foreignpolicy.com/feed/",
        "country": "US",
        "category": "geopolitics",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Reuters Commodities",
        "url": "https://www.reuters.com/markets/commodities",
        "rss_url": "https://feeds.reuters.com/reuters/commoditiesNews",
        "country": "US",
        "category": "commodities",
        "bias_rating": "center",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Radio Free Europe",
        "url": "https://www.rferl.org",
        "rss_url": "https://www.rferl.org/api/epiqq",
        "country": "US",
        "category": "geopolitics",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Brookings Institution",
        "url": "https://www.brookings.edu",
        "rss_url": "https://www.brookings.edu/feed/",
        "country": "US",
        "category": "policy",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "Carbon Brief",
        "url": "https://www.carbonbrief.org",
        "rss_url": "https://www.carbonbrief.org/feed/",
        "country": "UK",
        "category": "climate",
        "bias_rating": "left",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Crisis Group",
        "url": "https://www.crisisgroup.org",
        "rss_url": "https://www.crisisgroup.org/rss.xml",
        "country": "BE",
        "category": "conflict",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Straits Times",
        "url": "https://www.straitstimes.com",
        "rss_url": "https://www.straitstimes.com/rss.xml",
        "country": "SG",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Daily Nation Kenya",
        "url": "https://nation.africa",
        "rss_url": "https://nation.africa/kenya/rss.xml",
        "country": "KE",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "South China Morning Post",
        "url": "https://www.scmp.com",
        "rss_url": "https://www.scmp.com/rss/91/feed",
        "country": "HK",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "Deutsche Welle",
        "url": "https://www.dw.com",
        "rss_url": "https://rss.dw.com/rdf/rss-en-world",
        "country": "DE",
        "category": "general",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
    {
        "name": "The Guardian",
        "url": "https://www.theguardian.com",
        "rss_url": "https://www.theguardian.com/world/rss",
        "country": "UK",
        "category": "general",
        "bias_rating": "center-left",
        "bias_source": "allsides",
        "scrape_method": "rss",
    },
    {
        "name": "OilPrice",
        "url": "https://oilprice.com",
        "rss_url": "https://oilprice.com/rss/main",
        "country": "US",
        "category": "commodities",
        "bias_rating": "center",
        "bias_source": "mbfc",
        "scrape_method": "rss",
    },
]
