/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: {
          void:     "#050505",
          base:     "#0A0A0A",
          surface:  "#111111",
          elevated: "#181818",
          overlay:  "#1F1F1F",
        },
        border:          "#252525",
        "border-mid":    "#333333",
        "border-strong": "#444444",
        crimson: {
          DEFAULT: "rgba(var(--crimson-rgb), <alpha-value>)",
          light:   "#E52040",
          dim:     "#5A0018",
        },
        paper: "rgba(var(--paper-rgb), <alpha-value>)",
        ink:   "rgba(var(--ink-rgb),   <alpha-value>)",
        text: {
          primary:   "#F0EDE8",
          secondary: "#888880",
          muted:     "#4A4845",
          dim:       "#2A2825",
        },
      },
      fontFamily: {
        sans:    ["Inter", "system-ui", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
        display: ["'Bebas Neue'", "Impact", "sans-serif"],
      },
      fontSize: {
        "2xs": "0.6875rem",
        xs:    "0.75rem",
        sm:    "0.875rem",
        base:  "1rem",
        lg:    "1.125rem",
        xl:    "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
        "5xl": "3.25rem",
        "6xl": "4rem",
        "7xl": "5rem",
        "8xl": "6.5rem",
      },
      spacing: {
        px: "1px",
        0:  "0",
        1:  "4px",
        2:  "8px",
        3:  "12px",
        4:  "16px",
        5:  "20px",
        6:  "24px",
        7:  "28px",
        8:  "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
        32: "128px",
      },
      borderRadius: {
        none:    "0",
        sm:      "2px",
        DEFAULT: "4px",
        lg:      "6px",
        xl:      "8px",
        full:    "9999px",
      },
      animation: {
        "pulse-slow": "subtlePulse 3s ease-in-out infinite",
        "pulse-fast": "subtlePulse 1.5s ease-in-out infinite",
        spin:         "spin 1s linear infinite",
      },
      keyframes: {
        subtlePulse: {
          "0%, 100%": { opacity: "0.9" },
          "50%":      { opacity: "0.3" },
        },
      },
    },
  },
  plugins: [],
};
